[package]
name = "arkanoid"
version = "0.1.0"
authors = [
  "Gabriel Poittevin <gabriel.poittevin@gmail.com>"
]

[dependencies]
failure = "0.1.2"

[dependencies.sdl2]
version = "0.32.0"
features = ["gfx"]
